/**
 *
 * Requires pqfNotificationLib
 * 
 */

"use strict";

const MOCKING_MODE = false;
const DEBUG_MODE = true;
const TEST_RECEIVING_EMAIL_ADDRESSES = ["dh@pqforce.com"];

// What shall be done when this JS is executed manually?
// Options: "processOutbox" | "outboxMaintenance"
const DO_AT_MANUAL_EXECUTION = "outboxMaintenance";

// If DO_AT_MANUAL_EXECUTION == "outboxMaintenance":
// What shall be done with the outbox?
// Options: "showStatistics" | "initialize" | "empty"
const OUTBOX_MAINTENANCE_MODE = "showStatistics";

// Static email adresses that might to be notified in some rules
// (maybe empty array or null)
const NOTIFY_EMAIL_ADRESSES = ["some@static-email.com"];

// Array of resource IDs that might have to be notified in some rules
// (maybe empty array or null)
const NOTIFY_STATIC_RESOURCES = [];

// Object types for which notifications are generated
// (needed for outbox maintenance, which is not triggered by an object)
const OBJECT_TYPES = ["Project", "ProjectReport"];

// Specific user roles that are used in the notification rules
const PROJECT_PORTFOLIO_MANAGEMENT = "E8AF79B8995C417A9C601BFE2953918B"; 

// Project relations that are used in the notification rules
const PROJEKTLEITER = "06FCCCAAA5BD45FAAE0297E081D91FDE";
const AUFTRAGGEBER = "44D7E4AB2C7248BBAFF28E00F068FC4C";

// Project report states that are used in the notification rules
const RAPPORTIERUNG = "DCD4DE06744949D385716DD60822EFD0";
const ZU_GENEHMIGEN = "50B8FFA3E78048EE809F73FD298DD054";
const GENEHMIGT = "572718A12D5047978E5D358AB8A18FFF";

// Project states that are used in the notification rules
const FIRST_PHASE = "654E9F762EAA4C619BE4510E85D57B30";
const GATE = "7CA1663A55C640F88A0172E3D5AD9B97";
const SECOND_PHASE = "D483B3C3BEBC4CCD9080AC5D8C3ACF49";

// ----------------------------------------------------------------------
// Notification rules for lifecycle changes
// ----------------------------------------------------------------------
//
// Notification rules are specified as an array of JSON objects, each of which defines one rule.
//
// Each rule has the following components. Note that you can specify several rules for the same state in consideration.
//
// stateId: string | true. The ID of the lifecycle state in consideration. Can be true, meaning 'any state'.
// whenCommented: {
//		notifyStaticEmails: array of strings | null
//		notifyRelationTypes: array of string | null 
//		notifyUserRoles: array of strings | null
//		useEmailTemplate: function which generates subject and body of emails, see section 'Mail template functions' below for details and examples.
// }
// whenEnteringFromStateIds: Array of {
//		stateId: string | true. The ID of the lifecycle state the state in consideration was entered from (previous state). Can be true, meaning 'any state'.
//		notificationType: string. The type of notification. IMPORTANT: This string will be part of the ID that identifies the message if it goes to the outbox. Messages in the outbox can be updated or removed by their ID.
//		notifyStaticEmails: array of strings (email addresses) | null
//		notifyRelationTypes: array of string (IDs of relation types) | null 
//		notifyUserRoles: array of strings (IDs of user roles) | null
//		useEmailTemplate: function which returns {"subject": string, "body": string}, see section 'Mail template functions' below for examples
//		outboxOptions: { // If not present or null, the mails generated by this rule will be sent immediately
//			sendAtDays: null | array of non-negative integers.
//								Default is null.
//								If it contains 0 it means 'send immediately'.
//								Send that many days after the message has been put into the outbox.
//								**If this option is used, make sure that the outbox is processed daily**, see OUTBOX_PROCESSING_SCHEDULE.
//								USE THIS OPTION AS ALTERNATIVE TO 'repeatTimes'. If both options are set, 'sendAtDays' has preference.
//			repeatTimes: null | non-negative integer.
//								Default is 0.
//								Repeat sending the message with each outbox processing.
//								Note: Immediate send-out is NOT included in this number!
//								USE THIS OPTION AS ALTERNATIVE TO 'sendAtDays'. If both options are set, 'sendAtDays' has preference.
//			notBeforeDays: null | non-negative integer.
//								Default is 0.
//								0 or null means 'send immediately'.
//								Otherwise it combines with 'repeatTimes' and sends the first message not before that many days after today.
//			[same outboxOptions as below can also be used here: removeInfoItems - but they might not make that much sense here]
//		}
// }
// whenExitedToStateIds: Array of {
//		stateId: string | true. The ID of the lifecycle state the state in consideration was exited to (next state). Can be true, meaning 'any state'.
//		notificationType: string. The type of notification
//		notifyStaticEmails: array of strings (email addresses) | null
//		notifyRelationTypes: array of string (IDs of relation types) | null 
//		notifyUserRoles: array of strings (IDs of user roles) | null
//		useEmailTemplate: function which returns {"subject": string, "body": string}, see section 'Mail template functions' below for examples
//		useEmailTemplateForRequester: dito. This is to notify the user that has entered the state in consideration.
//		outboxOptions: { // If not present or null, the mails generated by this rule will be sent immediately
//			removeInfoItems: boolean.
//								Default is false.
//								Remove all info items from all envelopes matching the rule ID (stateId) and object ID.
//								Note: This option should NOT be used together with the above options in 'outboxOptions',
//								i.e., in one state transition rule we either put OR remove info items from the outbox.
//			[same outboxOptions as above can also be used here: sendAtDays, repeatTimes, notBeforeDays - but they might not make that much sense here]
//		}
// }
//

const NOTIFICATION_RULES =
[

	// An exemplary rule for PROJECT lifecycles
	// ----------------------------------------
    {
        "stateId": GATE,
        "whenCommented": {
            "notifyStaticEmails": NOTIFY_EMAIL_ADRESSES,
            "notifyStaticResources": NOTIFY_STATIC_RESOURCES,
            "useEmailTemplate": createProjectCommentMail
        },
        "whenEnteringFromStateIds": [
            {
                "stateId": FIRST_PHASE,
				"notificationType": "decisionRequired",
                "notifyRelationTypes": [ AUFTRAGGEBER ],
				"notifyUserRoles": [ PROJECT_PORTFOLIO_MANAGEMENT ],
                "useEmailTemplate": createProjectDecisionRequestMail,
				"outboxOptions": {
					"notBeforeDays": 1,
					"repeatTimes": 3
				}
            }
        ],
        "whenExitedToStateIds": [
            {
                "stateId": SECOND_PHASE,
				"notificationType": "decisionTaken",
				"notifyUserRoles": [ PROJECT_PORTFOLIO_MANAGEMENT ],
                "useEmailTemplate": createProjectDecisionInfoMail,
                "useEmailTemplateForRequester": createProjectDecisionInfoMail,
				"outboxOptions": {
					"removeInfoItems": true
				}
            }
        ]
    },
	
    // An exemplary rule for PROJECT REPORT lifecycles
	// -----------------------------------------------
    
    {
        "stateId": ZU_GENEHMIGEN,
        "whenCommented": {
            "notifyRelationTypes": [ {"hierarchy": "parent", "relationTypeId": AUFTRAGGEBER} ],
            "useEmailTemplate": createReportCommentMail
        },
        "whenEnteringFromStateIds": [
            {
                "stateId": RAPPORTIERUNG,
                "notifyRelationTypes": [ {"hierarchy": "parent", "relationTypeId": AUFTRAGGEBER} ],
                "useEmailTemplate": createReportApprovalRequestMail,
                "outboxOptions": {
                    "notBeforeDays": 0, // send immediately
                    "repeatTimes": 3
                }
            }
        ],
        "whenExitedToStateIds": [
            { // positive (request granted)
                "stateId": GENEHMIGT,
                "notifyRelationTypes": [ {"hierarchy": "parent", "relationTypeId": AUFTRAGGEBER} ],
                "useEmailTemplate": createReportDecisionPositiveMail,
                "useEmailTemplateForRequester": createReportDecisionPositiveMail,
                "outboxOptions": {
                    "removeInfoItems": true
                }
            },
            { // negative (request denied)
                "stateId": RAPPORTIERUNG,
                "notifyRelationTypes": [ AUFTRAGGEBER ],
                "useEmailTemplate": createReportDecisionNegativeMail,
                "useEmailTemplateForRequester": createReportDecisionNegativeMail,
                "outboxOptions": {
                    "removeInfoItems": true
                }
            }
        ]
    }

];

const OUTBOX_PROCESSING_SCHEDULE = {
	"quarterly": [], // Optional. Array with days of quarter, e.g., [1, 50] means every first and fiftieth day of a quarter
	"monthly": [], // Optional. Array with days of month, e.g., [1, 5] means every first and fifth day of a month
	"weekly": [1, 2, 3, 4, 5] // Optional. Array with days of week, where Sunday = 0, Monday = 1, e.g., [2, 4] means every Tuesday and Thursday, [1,2,3,4,5] means every working day	
};


// ----------------------------------------------------------------------
// Mail template skin
// ----------------------------------------------------------------------
//
// This object adjusts the mail skin used as template for the notification emails.
//
// The following parameters are available. Note that all parameters can also be omitted and then default to some predefined values.
//
//	darkFontColor: string (color, either HEX like, e.g., "#DB5656", or HTML color name like, e.g. "DarkRed", see https://www.w3schools.com/tags/ref_colornames.asp)
//	lightFontColor: dito
//	darkBackgroundColor: dito
//	lightBackgroundColor: dito
//	testingAlertFontColor: dito (used for the testing banner, see below)
//	testingAlertBackgroundColor: dito
//	logoSrc: string. URL pointing to an image that will be inserted at the header of the mail
//	logoLink: string. URL that will be inserted behind the image
//	logoAlt: string. Alternative text that will show if the mail client cannot display the image
//	bodyMessageMode: "dark" | "light" | "plain" | null. Defines the styling of the main part of the email body
//	textAlign: "left" | "center" | null. Defines the text alignment in the email body
//	testing": boolean // Creates a striking banner at the top of the notification email

const MAIL_SKIN =
{
	"darkFontColor": "#07074E", // PQFORCE dark blue
	"lightFontColor": "#FFFFFF", // white
	"darkBackgroundColor": "#DB5656", // PQFORCE red
	"lightBackgroundColor": "#F7F7F7", // light gray
	"testingAlertFontColor": "#FFFFFF", // white
	"testingAlertBackgroundColor": "#FF0000", // red
	"logoSrc": "https://www.pqforce.com/logo-colour-a.png",
	"logoLink": "https://www.pqforce.com",
	"logoAlt": "PQFORCE Logo",
	"bodyMessageMode": "plain",
	"textAlign": "left",
	"testing": MOCKING_MODE // Creates a striking banner at the top of the notification email
};

// Set parameters
pqfNotificationLib.setObjectTypes(OBJECT_TYPES);
pqfNotificationLib.setRules(NOTIFICATION_RULES);
pqfNotificationLib.setMockingMode(MOCKING_MODE);
pqfNotificationLib.setDebuggingMode(DEBUG_MODE);
pqfNotificationLib.setEmailSkin(MAIL_SKIN);
pqfNotificationLib.setOutboxProcessingParameters(OUTBOX_PROCESSING_SCHEDULE, OUTBOX_MAINTENANCE_MODE);

// Processing
if (typeof trigger === "undefined") {
	//
	// Outbox maintenance
	// ------------------
	//
	switch(DO_AT_MANUAL_EXECUTION) {
	    case "outboxMaintenance":
        	pqfNotificationLib.sendLifecycleNotifications();
        	break;
        default:
        	pqfNotificationLib.processOutbox();
	}
	
} else if(trigger.objectType === "Day") {
	//
	// Outbox processing
	// -----------------
	// For each message in the outbox, send it according to the parameters with which the message was put into the outbox.
	//
	pqfNotificationLib.processOutbox();
	
} else if(trigger.action === "LIFECYCLE") {
	//
	// Rules processing
	// ----------------
	// Process the triggering object, create the notification messages and send them according to the sending options, potentially put them into the outbox for later processing.
	//
	pqfNotificationLib.sendLifecycleNotifications(trigger.objectType, trigger.objectId);
}

// ----------------------------------------------------------------------
// Mail template functions
// ----------------------------------------------------------------------
//
// Such functions are used to generate notification emails. They get specific arguments (see below)
// that can be used to populate the subject and body of the email.
// Below you find examples of such functions and how the arguments can be used.
//
// Expected return value: {"subject": string, "body": string}
//
// Arguments received (in this order):
//
// receiverInfos = {
//		name: string (username)
//		email: string
//		resourceName: string | null (only present if user has resource)
//		roleName: string | null (only present if notified by role)
//		relationName: string | null (only present if notified by relation)
//		isRequester: boolean | null
//		requestText: string | null
// }
//
// actorInfos = {
//		name: string (username)
//		email: string
//		doNotify: boolean
//		mobile: string | null
//		resourceName: string | null (only present if user has resource)
//		previousActor = {
//			name: string (username)
//			email: string
//			doNotify: boolean
//			mobile: string | null
//			resourceName: string | null (only present if user has resource)
//		}
// }
//
// objectInfos = {
//		name: string
//		type: string
//		id: string
//		code: string
//		description: string
//		properties: array of JSON objects
//		subObjects: array of JSON objects
//		stateNow: {id: string, name: string}
//		stateBefore: {id: string, name: string}
//		url: string
//		portfolioName: string (multiple names are comma-separated)
//		parent = {
//			name: string
//			type: string
//			id: string
//			description: string
//			properties: array of JSON objects
//			subObjects: array of JSON objects
//			url: string
//		}
// }
//
// language: "de" | "fr" | "it" | "en-ch" | null
//
// outputType: "email" | "envelope" | "infoItem" | null
//


// Example 1: Notification for when a comment has been made
// --------------------------------------------------------

function createProjectCommentMail(receiverInfos, actorInfos, projectInfos, language, outputType) {
    let reason = "";
    let subject = "";	
    let body = "";
	switch(outputType) {
	case "infoItem":
		let html = "<p>";
		html += "Im Projekt <a href=\"" + projectInfos.url + "\"><b>" + projectInfos.name + "</b></a> wurde vom Benutzer <b>" + actorInfos.name + "</b> folgender Kommentar erfasst:" + "<br>";
		html += "<i>" + (projectInfos.comment ? projectInfos.comment : "[kein Kommentar erfasst]") + "</i>";
		if(receiverInfos.roleName) {
			reason = "Du erhältst diese Benachrichtigung, weil du die Benutzerrolle " + receiverInfos.roleName + " hast.";
		}
		if(receiverInfos.relationName) {
			reason = "Du erhältst diese Benachrichtigung, weil du zum Projekt die Beziehung " + receiverInfos.relationName + " hast.";
		}
		html += reason + "</p>";
		return html;
	case "envelope":
		switch(language) {
			case "en":
				subject = (projectInfos ? "New comment in project " + projectInfos.name : "New comments");
				break;
			default:
				subject = (projectInfos ? "Neuer Kommentar im Projekt " + projectInfos.name : "Neue Kommentare");
		}
        body = "<p>" + (receiverInfos.resourceName ? "Hallo " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hallo " + receiverInfos.name + "!" : "Hallo!")) + "</p>";
		body += pqfNotificationLib.infoItemsPlaceholderText;
		body += "<p>Diese Nachricht ist rein informativ. Es sind keine Aktionen von dir gefordert. Bitte antworte auch nicht auf diese E-Mail.</p>";
		body += "<p>Dein PQFORCE Notifikationssystem</p>";
		return {
			"subject": subject,
			"body": body
		};
	default: // includes "email":
		switch(language) {
			case "en":
				subject = (projectInfos ? "New comment in project " + projectInfos.name : "New comments");
				break;
			default:
				subject = (projectInfos ? "Neuer Kommentar im Projekt " + projectInfos.name : "Neue Kommentare");
		}
		body = "<p>" + (receiverInfos.resourceName ? "Hallo " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hallo " + receiverInfos.name + "!" : "Hallo!")) + "</p>";
		if(receiverInfos.roleName) {
			reason = "<p>Du erhältst diese Benachrichtigung, weil du die Benutzerrolle " + receiverInfos.roleName + " hast.</p>";
		}
		if(receiverInfos.relationName) {
			reason = "<p>Du erhältst diese Benachrichtigung, weil du zum Projekt die Beziehung " + receiverInfos.relationName + " hast.</p>";
		}
		body += reason;
		body += "<p>Diese Nachricht ist rein informativ. Es sind keine Aktionen von dir gefordert. Bitte antworte auch nicht auf diese E-Mail.</p>";
		body += "<p>Dein PQFORCE Notifikationssystem</p>";
		return {
			"subject": subject,
			"body": body
		};
	}
}

// Example 2: Notification for when a decision request has been made
// -----------------------------------------------------------------

function createProjectDecisionRequestMail(receiverInfos, actorInfos, projectInfos, language, outputType) {
	switch(outputType) {
	case "infoItem":
		return "";
		break;
	default:
		let subject = "Entscheidungsanfrage im Projekt " + projectInfos.name;
		let body = "<p>" + (receiverInfos.resourceName ? "Hallo " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hallo " + receiverInfos.name + "!" : "Hallo!")) + "</p>";
		body += "<p>Das Projekt " + projectInfos.name + " wurde vom Benutzer " + actorInfos.name + " in den Zustand " + projectInfos.stateNow.name + " gesetzt. Davor war es im Zustand " + projectInfos.stateBefore.name + ". Folgender Kommenter wurde dabei erfasst:</p>";
		body += "<p>" + (projectInfos.comment ? projectInfos.comment : "[kein Kommentar erfasst]") + "</p>";
		let reason = "";
		if(receiverInfos.roleName) {
			reason += "<p>Du erhältst diese Benachrichtigung, weil du die Benutzerrolle " + receiverInfos.roleName + " hast. Du bist damit berechtigt, eine Entscheidung zu treffen.</p>";
		}
		if(receiverInfos.relationName) {
			reason += "<p>Du erhältst diese Benachrichtigung, weil du zum Projekt die Beziehung " + receiverInfos.relationName + " hast. Du bist damit berechtigt, eine Entscheidung zu treffen.</p>";
		}
		if(reason) {
			body += reason;
		}
		if(receiverInfos.requestText) {
			body += "<p>" + receiverInfos.requestText + "</p>";
		}
		body += "<p>Mit diesem <a href=\"" + projectInfos.url + "\">Link</a> gelangst du direkt zum Projekt auf die Ansicht \"Details\", wo du den Lebenszyklus-Zustand verändern kannst. Bitte antworte nicht auf diese E-Mail.</p>";
		body += "<p>Dein PQFORCE Notifikationssystem</p>";
		return {
			"subject": subject,
			"body": body
		};
	}
}

// Example 3: Notification for when a decision has been taken
// ----------------------------------------------------------
function createProjectDecisionInfoMail(receiverInfos, actorInfos, projectInfos, language) {
    let subject = "Entscheidung im Projekt " + projectInfos.name + " gefällt";
    let body = "<p>" + (receiverInfos.resourceName ? "Hallo " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hallo " + receiverInfos.name + "!" : "Hallo!")) + "</p>";
    body += "<p>Das Projekt " + projectInfos.name + " wurde vom Benutzer " + actorInfos.name + " in den Zustand " + projectInfos.stateNow.name + " gesetzt. Folgender Kommenter wurde dabei erfasst:</p>";
    body += "<p>" + (projectInfos.comment ? projectInfos.comment : "[kein Kommentar erfasst]") + "</p>";
    if(receiverInfos.isRequester) {
        body += "<p>Du erhältst diese Benachrichtigung, weil du eine Entscheidung verlangt hast.</p>";
    }
    body += "<p>Mit diesem <a href=\"" + projectInfos.url + "\">Link</a> gelangst du direkt zum Projekt auf die Ansicht \"Details\".</p>";
    body += "<p>Diese Nachricht ist rein informativ. Es sind keine Aktionen von dir gefordert. Bitte antworte auch nicht auf diese E-Mail.</p>";
    body += "<p>Dein PQFORCE Notifikationssystem</p>";
    return {
        "subject": subject,
        "body": body
    };
}

// Example 4: Notification for when a project report has been commented
// --------------------------------------------------------------------
function createReportCommentMail(receiverInfos, actorInfos, objectInfos, language, outputType) {
    let subject = "";
    let body = "";
    let actorName = "";
    let reason = "";
    switch(outputType) {
    default: // This email template is only used to send ad hoc emails (no outboxing)
    	switch(language) {
    		case "en-ch":
    			subject = "New comment for status report " + objectInfos.name;
    			actorName = "[unknown]";
    			break;
    		case "fr":
    			subject = "Nouveau commentaire pour le rapport de statut " + objectInfos.name;
    			actorName = "[unconnu]";
    			break;
    		default:
    			subject = "Neuer Kommentar zum Statusbericht " + objectInfos.name;
    			actorName = "[unbekannt]";
    	}
    	actorName = (actorInfos && actorInfos.resourceName ? actorInfos.resourceName : (actorInfos && actorInfos.name ? actorInfos.name : actorName)) + (actorInfos && actorInfos.email ? " (" + actorInfos.email + ")" : "");
    	let receiverName = (receiverInfos.resourceName ? receiverInfos.resourceName  : (receiverInfos.name ? receiverInfos.name : null));
        body = greeting(receiverInfos, language);
        switch(language) {
            case "en-ch":
                body += "<p>User <b>" + actorName + "</b> has added the following comment on the status report <b>" + objectInfos.name + "</b> of the project <b>" + (objectInfos.parent ? objectInfos.parent.name : "[unknown]") + "</b>:</p>";
                body += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[no comment]") + "</i></p>";
                if(receiverInfos.roleName) {
                    reason = "<p>Your receive this notification because you have the user role " + receiverInfos.roleName + ".</p>";
                }
                if(receiverInfos.relationName) {
                    reason = "<p>Your receive this notification because you have the relation " + receiverInfos.relationName + " to the project.</p>";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>With this <a href=\"" + objectInfos.url + "\">link</a> you directly get to the status report.</p>";
                body += "<p>This is just an information. You don't need to take action. Please do not reply to this email.</p>";
                body += "<p>Your PQFORCE notification system</p>";
                break;
            case "fr":
                body += "<p>Utilisateur <b>" + actorName + "</b> a ajouté le commentaire suivant au rapport de statut <b>" + objectInfos.name + "</b> du projet <b>" + (objectInfos.parent ? objectInfos.parent.name : "[unconnu]") + "</b>:</p>";
                body += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[pas de commentaire]") + "</i></p>";
                if(receiverInfos.roleName) {
                    reason = "<p>Vous recevez cette notification parce que vous avez le rôle d'utilisateur " + receiverInfos.roleName + ".</p>";
                }
                if(receiverInfos.relationName) {
                    reason = "<p>Vous recevez cette notification parce que vous êtes en relation " + receiverInfos.relationName + " avec le projet.</p>";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>Ce <a href=\"" + objectInfos.url + "\">lien</a> vous permet d'accéder directement au rapport de situation.</p>";
                body += "<p>Il s'agit simplement d'une information. Vous n'avez pas besoin d'agir. Ne répondez pas à cet e-mail.</p>";
                body += "<p>Système de notification PQFORCE</p>";
                break;
            default:
                body += "<p>Benutzer <b>" + actorName + "</b> hat zum Statusberich <b>" + objectInfos.name + "</b> zum Projekt <b>" + (objectInfos.parent ? objectInfos.parent.name : "[unbekannt]") + "</b> folgenden Kommentar erfasst:" + "</p>";
                body += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[kein Kommentar]") + "</i></p>";
                if(receiverInfos.roleName) {
                    reason = "<p>Du erhältst diese Benachrichtigung, weil du die Benutzerrolle " + receiverInfos.roleName + " hast.</p>";
                }
                if(receiverInfos.relationName) {
                    reason = "<p>Du erhältst diese Benachrichtigung, weil du die Beziehung " + receiverInfos.relationName + " zum Projekt hast.</p>";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>Mit diesem <a href=\"" + objectInfos.url + "\">Link</a> gelangst du direkt zum Statusbericht.</p>";
                body += "<p>Diese Nachricht ist rein informativ. Es sind keine Aktionen von dir gefordert. Bitte antworte auch nicht auf diese E-Mail.</p>";
                body += "<p>Dein PQFORCE Notifikationssystem</p>";
        }
        return {
            "subject": subject,
            "body": body
        };
    }
}

// Example 5: Notification for when a report decision needs to be taken
// --------------------------------------------------------------------
function createReportApprovalRequestMail(receiverInfos, actorInfos, objectInfos, language, outputType) {
    let subject = "";
    let body = "";
    let actorName = "";
	switch(language) {
		case "en-ch":
			actorName = "[unknown]";
			break;
		case "fr":
			actorName = "[unconnu]";
			break;
		default:
			actorName = "[unbekannt]";
	}
	actorName = (actorInfos && actorInfos.resourceName ? actorInfos.resourceName : (actorInfos && actorInfos.name ? actorInfos.name : actorName)) + (actorInfos && actorInfos.email ? " (" + actorInfos.email + ")" : "");
	let reason = "";
    switch(outputType) {
    case "envelope":
    	switch(language) {
    		case "en-ch":
    			subject = "Reminder: Pending project report approval requests";
    			break;
    		case "fr":
    			subject = "Rappel: Demandes de decision en attente";
    			break;
    		default:
    			subject = "Erinnerung: Pendente Genehmigungsanfragen zu Projektstatusberichten";
    	}
    	body = greeting(receiverInfos, language);
    	switch(language) {
    		case "en-ch":
        		body += "<p>This is a reminder that the following status reports need an approval:</p>";
        		body += pqfNotificationLib.infoItemsPlaceholderText;
        		body += "<p>Please check and answer the above requests as soon as possible by clicking on the respective link. This will take you directly to the respective status report where you can change the life cycle status. Please do not reply to this e-mail.</p>";
        		body += "<p>Your PQFORCE notification system</p>";
    		    break;
    		case "fr":
        		body += "<p>Voici un rappel que les suivantes demande de decision sont en attente:</p>";
        		body += pqfNotificationLib.infoItemsPlaceholderText;
        		body += "<p>Veuillez vérifier les demandes ci-dessus et y répondre le plus rapidement possible en cliquant sur le lien correspondant. Tu arriveras ainsi directement au rapport d'état correspondant, où tu pourras modifier l'état du cycle de vie. Ne réponds pas à cet e-mail.</p>";
        		body += "<p>Système de notifications de PQFORCE</p>";
    		    break;
    	    default:
        		body += "<p>Dies ist eine Erinnerung, dass folgende Projektstatusberichte eine Genehmigung erfordern:</p>";
        		body += pqfNotificationLib.infoItemsPlaceholderText;
        		body += "<p>Bitte prüfe und beantworte die obigen Anfragen so rasch wie möglich, indem du auf den jeweiligen Link klickst. Du gelangst damit direkt zum jeweiligen Statusbericht, wo do den Lebenszyklus-Zustand verändern kannst. Bitte antworte nicht auf diese E-Mail.</p>";
        		body += "<p>Dein PQFORCE Notifikationssystem</p>";
    	}
        return {
            "subject": subject,
            "body": body
        };
        
	case "infoItem":
		let text = "";
		switch(language) {
		    case "en-ch":
        		text += "<p>For status report <a href=\"" + objectInfos.url + "\"><b>" + objectInfos.name + "</b></a> in project <b>" + objectInfos.parent.name + "</b> the user <b>" + actorName + "</b> added the following comment on " + moment(actorInfos.timestamp).format("DD.MM.YYYY, HH:mm") + ":</p>";
        		text += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[no comment]") + "</i></p>";
        		if(receiverInfos.roleName) {
        			reason = "<p>You receive this request because you have the user role " + receiverInfos.roleName + ".</p>";
        		}
        		if(receiverInfos.relationName) {
        			reason = "<p>You receive this request because you have the relation " + receiverInfos.relationName + " to the project.</p>";
        		}
        		text += reason;
		        break;
		    case "fr":
        		text += "<p>Pour le rapport de status <a href=\"" + objectInfos.url + "\"><b>" + objectInfos.name + "</b></a> du project <b>" + objectInfos.parent.name + "</b> l'utilisateur <b>" + actorName + "</b> en " + moment(actorInfos.timestamp).format("DD.MM.YYYY, HH:mm") + " a écrit le suivant commentaire:</p>";
        		text += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[pas de commentaire]") + "</i></p>";
        		if(receiverInfos.roleName) {
        			reason = "<p>Tu reçois cette demande parce que tu a le rôle d'utilisateur " + receiverInfos.roleName + ".</p>";
        		}
        		if(receiverInfos.relationName) {
        			reason = "<p>Tu reçois cette demande parce que tu as la relation " + receiverInfos.relationName + " avec le projet.</p>";
        		}
        		text += reason;
		        break;
		    default:
        		text += "<p>Im pendenten Statusbericht <a href=\"" + objectInfos.url + "\"><b>" + objectInfos.name + "</b></a> zu Projekt <b>" + objectInfos.parent.name + "</b> wurde vom Benutzer <b>" + actorName + "</b> am " + moment(actorInfos.timestamp).format("DD.MM.YYYY, HH:mm") + " folgender Kommentar erfasst:" + "</p>";
        		text += "<p><i>" + (objectInfos.comment ? objectInfos.comment : "[kein Kommentar erfasst]") + "</i></p>";
        		if(receiverInfos.roleName) {
        			reason = "<p>Du erhältst diese Anfrage, weil du die Benutzerrolle " + receiverInfos.roleName + " hast.</p>";
        		}
        		if(receiverInfos.relationName) {
        			reason = "<p>Du erhältst diese Anfrage, weil du zum Projekt die Beziehung " + receiverInfos.relationName + " hast.</p>";
        		}
        		text += reason;
		}

		let html = pqfLib.mail.getHtmlMessageTemplate("dark"); // contains placeholder: [[TextAlign]], [[BodyMessageBackgroundColor]], [[BodyMessageFontColor]], [[Message]]
		html = pqfLib.utils.format.replaceAll(html, "[[TextAlign]]", "left");
		html = pqfLib.utils.format.replaceAll(html, "[[BodyMessageBackgroundColor]]", "#F7F7F7");
		html = pqfLib.utils.format.replaceAll(html, "[[BodyMessageFontColor]]", "#07074E");
		html = pqfLib.utils.format.replaceAll(html, "[[Message]]", text);
		
		return html;
		
    default: // includes "email"
    	switch(language) {
    		case "en-ch":
    			subject = "Approval requests for status report " + objectInfos.name;
    			break;
    		case "fr":
    			subject = "Demandes de decision pour le rapport de statut " + objectInfos.name;
    			break;
    		default:
    			subject = "Genehmigungsanfrage zum Projektstatusbericht " + objectInfos.name;
    	}
    	let receiverName = (receiverInfos.resourceName ? receiverInfos.resourceName  : (receiverInfos.name ? receiverInfos.name : null));
        reason = "";
    	body = greeting(receiverInfos, language);
        switch(language) {
            case "en-ch":
                body += "<p>User <b>" + actorName + "</b> has submitted the status report <b>" + objectInfos.name + "</b> in project <b>" + objectInfos.parent.name + "</b> for approval.";
                if(objectInfos.comment) {
                    body += " They have added the following comment:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.roleName) {
                    reason = "<p>You receive this notification because you have the user role " + receiverInfos.roleName + ". You are therefore authorized to approve or reject the status report.</p>";
                }
                if(receiverInfos.relationName) {
                    reason = "<p>You receive this notification because you have the relationship " + receiverInfos.relationName + " to the project. You are therefore authorized to approve or reject the status report.</p>";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>This <a href=\"" + objectInfos.url + "\">link</a> will take you directly to the status report, where you can change the lifecycle state and thus approve or reject the status report. Please do not reply to this email.</p>";
                body += "<p>Your PQFORCE notification system</p>";
                break;
            case "fr":
                body += "L'utilisateur <b>" + actorName + "</b> a soumis le rapport d'état <b>" + objectInfos.name + "</b> du projet <b>" + objectInfos.parent.name + "</b> pour approbation.";
                if(objectInfos.comment) {
                    body += " Ils ont ajouté le commentaire suivant:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.roleName) {
                    reason = "<p>Vous recevez cette notification parce que vous avez le rôle d'utilisateur " + receiverInfos.roleName + ". Vous êtes donc autorisé à approuver ou à rejeter le rapport d'état.</p>";
                }
                if(receiverInfos.relationName) {
                    reason = "<p>Vous recevez cette notification parce que vous avez la relation " + receiverInfos.relationName + " avec le projet. Vous êtes donc autorisé à approuver ou à rejeter le rapport d'état.";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>Ce <a href=\"" + objectInfos.url + "\">lien</a> te mènera directement au rapport d'état, où tu pourras modifier l'état du cycle de vie et ainsi approuver ou rejeter le rapport d'état. Ne réponds pas à cet e-mail.</p>";
                body += "<p>Système de notifications de PQFORCE</p>";
                break;
            default:
                body += "<p>Benutzer <b>" + actorName + "</b> hat den Statusbericht <b>" + objectInfos.name + "</b> im Projekt <b>" + objectInfos.parent.name + "</b> zur Genehmigung übergeben.";
                if(objectInfos.comment) {
                    body += " Folgender Kommentar wurde dabei erfasst:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.roleName) {
                    reason += "<p>Du erhältst diese Benachrichtigung, weil du die Benutzerrolle " + receiverInfos.roleName + " hast. Du bist damit berechtigt, den Statusbericht zu genehmigen oder zurückzuweisen.</p>";
                }
                if(receiverInfos.relationName) {
                    reason += "<p>Du erhältst diese Benachrichtigung, weil du zum Projekt die Beziehung " + receiverInfos.relationName + " hast. Du bist damit berechtigt, den Statusbericht zu genehmigen oder zurückzuweisen.</p>";
                }
                if(reason) {
                    body += reason;
                }
                body += "<p>Mit diesem <a href=\"" + objectInfos.url + "\">Link</a> gelangst du direkt zum Statusbericht, wo do den Lebenszyklus-Zustand verändern und den Statusbericht somit genehmigen oder zurückweisen kannst. Bitte antworte nicht auf diese E-Mail.</p>";
                body += "<p>Dein PQFORCE Notifikationssystem</p>";
        }
        return {
            "subject": subject,
            "body": body
        };
    }
}

// Example 6: Notification for when a positive report decision has been taken (report approved)
// --------------------------------------------------------------------------------------------
function createReportDecisionPositiveMail(receiverInfos, actorInfos, objectInfos, language, outputType) {
    let subject = "";
    let body = "";
    let actorName = "";
    switch(outputType) {
    default: // This email template is only used to send ad hoc emails (no outboxing)
    	switch(language) {
    		case "en-ch":
    			subject = "Status report " + objectInfos.name + " approved";
    			actorName = "[unknown]";
    			break;
    		case "fr":
    			subject = "Rapport de statut " + objectInfos.name + " accepté";
    			actorName = "[unconnu]";
    			break;
    		default:
    			subject = "Statusbericht " + objectInfos.name + " genehmigt";
    			actorName = "[unbekannt]";
    	}
    	actorName = (actorInfos && actorInfos.resourceName ? actorInfos.resourceName : (actorInfos && actorInfos.name ? actorInfos.name : actorName)) + (actorInfos && actorInfos.email ? " (" + actorInfos.email + ")" : "");
    	let receiverName = (receiverInfos.resourceName ? receiverInfos.resourceName  : (receiverInfos.name ? receiverInfos.name : null));
    	body = greeting(receiverInfos, language);
        switch(language) {
            case "en-ch":
                body += "<p>Good news 👍! User <b>" + actorName + "</b> has <i>accepted</i> the status report <b>" + objectInfos.name +  "</b>.";
                if(objectInfos.comment) {
                    body += " They have added the following comment:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>You are receiving this notification because you have submitted the status report for approval.</p>";
                } else {
                    body += "<p>You are receiving this notification because you could have approved the status report, but " + actorName + " has now done this in your place.</p>";
                }
                body += "<p>With this <a href=\"" + objectInfos.url + "\">link</a> you directly get to the status report to see further details.</p>";
                body += "<p>This is just an information. You don't need to take action. Please do not reply to this email.</p>";
                body += "<p>Your PQFORCE notification system</p>";
                break;
            case "fr":
                body += "<p>Bonnes nouvelles 👍! <b>L'utilisateur " + actorName + "</b> a <i>approuvé</i> le rapport d'état <b>" + objectInfos.name + "</b>.";
                if(objectInfos.comment) {
                    body += " Le commentaire suivant a été saisi:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>Tu reçois cette notification parce que tu as soumis le rapport d'état pour approbation.</p>";
                } else {
                    body += "<p>Tu reçois cette notification parce que tu aurais pu approuver le rapport d'état, mais " + actorName + " l'a fait à ta place.</p>";
                }
                body += "<p>Ce <a href=\"" + objectInfos.url + "\">lien</a> te permet d'accéder directement au rapport d'état pour voir plus de détails.</p>";
                body += "<p>Ce message est purement informatif. Aucune action n'est requise de ta part. Ne réponds pas non plus à cet e-mail.</p>";
                body += "<p>Système de notification PQFORCE</p>";
                break;
            default:
                body += "<p>Gute Neuigkeiten 👍! <b>Benutzer " + actorName + "</b> hat den Statusbericht <b>" + objectInfos.name + "</b> <i>genehmigt</i>.";
                if(objectInfos.comment) {
                    body += " Folgender Kommentar wurde dabei erfasst:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>Du erhältst diese Benachrichtigung, weil du den Statusbericht zur Genehmigung übergeben hast.</p>";
                } else {
                    body += "<p>Du erhältst diese Benachrichtigung, weil du den Statusbericht auch hättest genehmigen können, aber " + actorName + " dies nun an deiner Stelle übernommen hat.</p>";
                }
                body += "<p>Mit diesem <a href=\"" + objectInfos.url + "\">Link</a> gelangst du direkt zum Statusbericht, um weitere Details zu sehen.</p>";
                body += "<p>Diese Nachricht ist rein informativ. Es sind keine Aktionen von dir gefordert. Bitte antworte auch nicht auf diese E-Mail.</p>";
                body += "<p>Dein PQFORCE Notifikationssystem</p>";
        }
        return {
            "subject": subject,
            "body": body
        };
    }
}

// Example 7: Notification for when a negative report decision has been taken (report rejected)
// --------------------------------------------------------------------------------------------
function createReportDecisionNegativeMail(receiverInfos, actorInfos, objectInfos, language, outputType) {
    let subject = "";
    let body = "";
    let actorName = "";
    switch(outputType) {
    default: // This email template is only used to send ad hoc emails (no outboxing)
    	switch(language) {
    		case "en-ch":
    			subject = "Status report " + objectInfos.name + " rejected";
    			actorName = "[unknown]";
    			break;
    		case "fr":
    			subject = "Rapport de statut " + objectInfos.name + " rejeté";
    			actorName = "[unconnu]";
    			break;
    		default:
    			subject = "Statusbericht " + objectInfos.name + " zurückgewiesen";
    			actorName = "[unbekannt]";
    	}
    	actorName = (actorInfos && actorInfos.resourceName ? actorInfos.resourceName : (actorInfos && actorInfos.name ? actorInfos.name : actorName)) + (actorInfos && actorInfos.email ? " (" + actorInfos.email + ")" : "");
    	let receiverName = (receiverInfos.resourceName ? receiverInfos.resourceName  : (receiverInfos.name ? receiverInfos.name : null));
    	body = greeting(receiverInfos, language);
        switch(language) {
            case "en-ch":
                body += "<p>Bad news 👎! User <b>" + actorName + "</b> has <i>rejected</i> the status report <b>" + objectInfos.name +  "</b>.";
                if(objectInfos.comment) {
                    body += " They have added the following comment:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>You are receiving this notification because you have submitted the status report for approval.</p>";
                } else {
                    body += "<p>You are receiving this notification because you could have approved or rejected the status report, but " + actorName + " has now done this in your place.</p>";
                }
                body += "<p>With this <a href=\"" + objectInfos.url + "\">link</a> you directly get to the status report to see further details.</p>";
                body += "<p>This is just an information. Please do not reply to this email.</p>";
                body += "<p>Your PQFORCE notification system</p>";
                break;
            case "fr":
                body += "<p>Mauvaises nouvelles 👎! <b>L'utilisateur " + actorName + "</b> a <i>rejété</i> le rapport d'état <b>" + objectInfos.name + "</b>.";
                if(objectInfos.comment) {
                    body += " Le commentaire suivant a été saisi:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>Tu reçois cette notification parce que tu as soumis le rapport d'état pour approbation.</p>";
                } else {
                    body += "<p>Tu reçois cette notification parce que tu aurais pu approuver le rapport d'état, mais " + actorName + " l'a fait à ta place.</p>";
                }
                body += "<p>Ce <a href=\"" + objectInfos.url + "\">lien</a> te permet d'accéder directement au rapport d'état pour voir plus de détails.</p>";
                body += "<p>Ce message est purement informatif. Aucune action n'est requise de ta part. Ne réponds pas non plus à cet e-mail.</p>";
                body += "<p>Système de notification PQFORCE</p>";
                break;
            default:
                body += "<p>Schlechte Neuigkeiten 👎! <b>Benutzer " + actorName + "</b> hat den Statusbericht <b>" + objectInfos.name + "</b> <i>zurückgewiesen</i>.";
                if(objectInfos.comment) {
                    body += " Folgender Kommentar wurde dabei erfasst:</p>";
                    body += "<p><i>" + objectInfos.comment + "</i></p>";
                } else {
                    body += "</p>";
                }
                if(receiverInfos.isRequester) {
                    body += "<p>Du erhältst diese Benachrichtigung, weil du den Statusbericht zur Genehmigung übergeben hast.</p>";
                } else {
                    body += "<p>Du erhältst diese Benachrichtigung, weil du den Statusbericht auch hättest genehmigen oder zurückweisen können, aber " + actorName + " dies nun an deiner Stelle übernommen hat.</p>";
                }
                body += "<p>Mit diesem <a href=\"" + objectInfos.url + "\">Link</a> gelangst du direkt zum Statusbericht, um weitere Details zu sehen.</p>";
                body += "<p>Diese Nachricht ist rein informativ. Bitte antworte auch nicht auf diese E-Mail.</p>";
                body += "<p>Dein PQFORCE Notifikationssystem</p>";
        }
        return {
            "subject": subject,
            "body": body
        };
    }
}

// Helper function

function greeting(receiverInfos, lang) {
    switch(lang) {
        case "en-ch":
            return "<p>" + (receiverInfos.resourceName ? "Hello " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hello " + receiverInfos.name + "!" : "Hello!")) + "</p>";
        case "fr":
            return "<p>" + (receiverInfos.resourceName ? "Salut " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Salut " + receiverInfos.name + "!" : "Salut!")) + "</p>";
        default:
            return "<p>" + (receiverInfos.resourceName ? "Hallo " + receiverInfos.resourceName + "!" : (receiverInfos.name ? "Hallo " + receiverInfos.name + "!" : "Hallo!")) + "</p>";
    }
}